"""remove unnecessary column

Revision ID: 2e2c836bac10
Revises: 5ece6e103171
Create Date: 2024-06-20 20:05:25.115954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e2c836bac10'
down_revision = '5ece6e103171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_accommodations_student_id_students', type_='foreignkey')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_accommodations_student_id_students', 'students', ['student_id'], ['id'])

    # ### end Alembic commands ###
