"""change many to many relationship

Revision ID: 5ece6e103171
Revises: 92bb5714ab43
Create Date: 2024-06-20 19:52:04.013144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ece6e103171'
down_revision = '92bb5714ab43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students_accommodations',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('accommodation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], name=op.f('fk_students_accommodations_accommodation_id_accommodations')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_students_accommodations_student_id_students')),
    sa.PrimaryKeyConstraint('student_id', 'accommodation_id')
    )
    op.drop_table('accommodations_comments')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accommodation_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_comments_accommodation_id_accommodations'), 'accommodations', ['accommodation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comments_accommodation_id_accommodations'), type_='foreignkey')
        batch_op.drop_column('accommodation_id')

    op.create_table('accommodations_comments',
    sa.Column('accommodation_id', sa.INTEGER(), nullable=False),
    sa.Column('comment_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], name='fk_accommodations_comments_accommodation_id_accommodations'),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name='fk_accommodations_comments_comment_id_comments'),
    sa.PrimaryKeyConstraint('accommodation_id', 'comment_id')
    )
    op.drop_table('students_accommodations')
    # ### end Alembic commands ###
