"""add column to many to many table

Revision ID: 6471b35f82c8
Revises: 2e2c836bac10
Create Date: 2024-06-21 14:38:44.454841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6471b35f82c8'
down_revision = '2e2c836bac10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    with op.batch_alter_table('students_accommodations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students_accommodations', schema=None) as batch_op:
        batch_op.drop_column('comments')

    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('accommodation_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], name='fk_comments_accommodation_id_accommodations'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
