"""add description to comments table

Revision ID: 781aa4b75224
Revises: 84e3ce8d2067
Create Date: 2024-06-20 19:22:19.730817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781aa4b75224'
down_revision = '84e3ce8d2067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
