"""initial migration

Revision ID: 84e3ce8d2067
Revises: 
Create Date: 2024-06-20 17:59:11.703719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e3ce8d2067'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_students_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accommodations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_accommodations_student_id_students')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accommodation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], name=op.f('fk_comments_accommodation_id_accommodations')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accommodations_comments',
    sa.Column('accommodation_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], name=op.f('fk_accommodations_comments_accommodation_id_accommodations')),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('fk_accommodations_comments_comment_id_comments')),
    sa.PrimaryKeyConstraint('accommodation_id', 'comment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accommodations_comments')
    op.drop_table('comments')
    op.drop_table('accommodations')
    op.drop_table('students')
    op.drop_table('users')
    # ### end Alembic commands ###
