"""add many to many table

Revision ID: c7a31d639172
Revises: c8b1cdaf069a
Create Date: 2024-06-22 14:14:50.166552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a31d639172'
down_revision = 'c8b1cdaf069a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_classes_student_id_students')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students_accommodations',
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('accommodation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], name=op.f('fk_students_accommodations_accommodation_id_accommodations')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_students_accommodations_student_id_students')),
    sa.PrimaryKeyConstraint('student_id', 'accommodation_id')
    )
    op.drop_table('comments')
    with op.batch_alter_table('accommodations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_accommodations_student_id_students', type_='foreignkey')
        batch_op.drop_column('student_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('accommodations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_accommodations_student_id_students', 'students', ['student_id'], ['id'])

    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('accommodation_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], name='fk_comments_accommodation_id_accommodations'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('students_accommodations')
    op.drop_table('classes')
    # ### end Alembic commands ###
